import React, { useState, useRef } from "react";
import {
  View,
  Text,
  TextInput,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
} from "react-native";
import { useLocalSearchParams, Stack } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { getDomainConfig } from "../../constants/config";
import { Colors } from "../../constants/theme";
import { askDomain, AskResponse } from "../../services/api";
import { ChatMessage } from "../../components/ChatMessage";

interface Message {
  id: string;
  role: "user" | "assistant";
  text: string;
  chart?: AskResponse["chart"];
  sql?: AskResponse["sql"];
  elapsedMs?: number;
}

export default function DomainChatScreen() {
  const { name } = useLocalSearchParams<{ name: string }>();
  const domain = getDomainConfig(name || "reliability");
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const flatListRef = useRef<FlatList>(null);

  const sendMessage = async () => {
    const question = input.trim();
    if (!question || loading) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      text: question,
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const response = await askDomain(name || "reliability", question);

      // Extract a clean text summary from the response
      let displayText = response.response;
      // If the response contains "Results:" section, show from there
      const resultsIdx = displayText.indexOf("Results:\n");
      if (resultsIdx !== -1) {
        displayText = displayText.substring(resultsIdx + "Results:\n".length);
      }
      // Trim the model attribution line
      const modelIdx = displayText.lastIndexOf("\n\n_SQL generated by");
      if (modelIdx !== -1) {
        displayText = displayText.substring(0, modelIdx);
      }
      displayText = displayText.trim();

      const assistantMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        text: displayText,
        chart: response.chart,
        sql: response.sql,
        elapsedMs: response.elapsed_ms,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (error: any) {
      const errorMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        text: `Error: ${error.message}`,
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Stack.Screen
        options={{
          title: domain?.label || name || "Chat",
          headerStyle: { backgroundColor: domain?.color || Colors.primary },
          headerTintColor: "#ffffff",
        }}
      />

      <KeyboardAvoidingView
        style={styles.container}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        keyboardVerticalOffset={90}
      >
        <FlatList
          ref={flatListRef}
          data={messages}
          keyExtractor={(item) => item.id}
          renderItem={({ item }) => (
            <ChatMessage
              role={item.role}
              text={item.text}
              chart={item.chart}
              sql={item.sql}
              elapsedMs={item.elapsedMs}
            />
          )}
          contentContainerStyle={styles.messageList}
          onContentSizeChange={() => flatListRef.current?.scrollToEnd({ animated: true })}
          ListEmptyComponent={
            <View style={styles.emptyState}>
              <Ionicons name={domain?.icon || "chatbubbles"} size={48} color={Colors.border} />
              <Text style={styles.emptyText}>
                Ask anything about {domain?.label || "this domain"}
              </Text>
              <Text style={styles.emptyHint}>
                Try: "How many employees?" or "Show me a bar chart"
              </Text>
            </View>
          }
        />

        {loading && (
          <View style={styles.loadingBar}>
            <ActivityIndicator size="small" color={Colors.primary} />
            <Text style={styles.loadingText}>Thinking...</Text>
          </View>
        )}

        <View style={styles.inputContainer}>
          <TextInput
            style={styles.input}
            value={input}
            onChangeText={setInput}
            placeholder="Ask a question..."
            placeholderTextColor={Colors.textSecondary}
            multiline
            maxLength={500}
            returnKeyType="send"
            onSubmitEditing={sendMessage}
            blurOnSubmit={false}
          />
          <TouchableOpacity
            style={[styles.sendButton, (!input.trim() || loading) && styles.sendButtonDisabled]}
            onPress={sendMessage}
            disabled={!input.trim() || loading}
          >
            <Ionicons name="send" size={20} color="#ffffff" />
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  messageList: {
    paddingVertical: 12,
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  emptyText: {
    fontSize: 16,
    color: Colors.textSecondary,
    marginTop: 12,
  },
  emptyHint: {
    fontSize: 13,
    color: Colors.border,
    marginTop: 4,
    fontStyle: "italic",
  },
  loadingBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  loadingText: {
    marginLeft: 8,
    fontSize: 13,
    color: Colors.textSecondary,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.background,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.text,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  sendButtonDisabled: {
    backgroundColor: Colors.border,
  },
});
