import React, { useState, useRef } from "react";
import {
  View,
  Text,
  TextInput,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
} from "react-native";
import { Stack } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { Colors } from "../constants/theme";
import { getDomainLabel } from "../constants/config";
import { askAuto, RouterAskResponse } from "../services/api";
import { ChatMessage } from "../components/ChatMessage";

interface Message {
  id: string;
  role: "user" | "assistant";
  text: string;
  domains?: string[];
  routingMethod?: string;
  chart?: RouterAskResponse["chart"];
  sql?: RouterAskResponse["sql"];
  elapsedMs?: number;
}

export default function UniversalChatScreen() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const flatListRef = useRef<FlatList>(null);

  const sendMessage = async () => {
    const question = input.trim();
    if (!question || loading) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      text: question,
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setLoading(true);

    try {
      const response = await askAuto(question);

      let displayText = response.response;
      const resultsIdx = displayText.indexOf("Results:\n");
      if (resultsIdx !== -1) {
        displayText = displayText.substring(resultsIdx + "Results:\n".length);
      }
      const modelIdx = displayText.lastIndexOf("\n\n_SQL generated by");
      if (modelIdx !== -1) {
        displayText = displayText.substring(0, modelIdx);
      }
      displayText = displayText.trim();

      const assistantMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        text: displayText,
        domains: response.domains,
        routingMethod: response.routing_method,
        chart: response.chart,
        sql: response.sql,
        elapsedMs: response.elapsed_ms,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (error: any) {
      const errorMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        text: `Error: ${error.message}`,
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Stack.Screen
        options={{
          title: "COOPER",
          headerStyle: { backgroundColor: Colors.background },
          headerTintColor: Colors.text,
        }}
      />

      <KeyboardAvoidingView
        style={styles.container}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        keyboardVerticalOffset={90}
      >
        <FlatList
          ref={flatListRef}
          data={messages}
          keyExtractor={(item) => item.id}
          renderItem={({ item }) => (
            <View>
              {item.role === "assistant" && item.domains && item.domains.length > 0 && (
                <View style={styles.domainBadges}>
                  {item.domains.map((d) => (
                    <View key={d} style={styles.badge}>
                      <Text style={styles.badgeText}>{getDomainLabel(d)}</Text>
                    </View>
                  ))}
                </View>
              )}
              <ChatMessage
                role={item.role}
                text={item.text}
                chart={item.chart}
                sql={item.sql}
                elapsedMs={item.elapsedMs}
              />
            </View>
          )}
          contentContainerStyle={styles.messageList}
          onContentSizeChange={() =>
            flatListRef.current?.scrollToEnd({ animated: true })
          }
          ListEmptyComponent={
            <View style={styles.emptyState}>
              <Ionicons name="chatbubbles" size={48} color={Colors.border} />
              <Text style={styles.emptyText}>Ask anything about SMECO data</Text>
              <Text style={styles.emptyHint}>
                COOPER will automatically route to the right domain
              </Text>
            </View>
          }
        />

        {loading && (
          <View style={styles.loadingBar}>
            <ActivityIndicator size="small" color={Colors.primary} />
            <Text style={styles.loadingText}>Routing & thinking...</Text>
          </View>
        )}

        <View style={styles.inputContainer}>
          <TextInput
            style={styles.input}
            value={input}
            onChangeText={setInput}
            placeholder="Ask a question..."
            placeholderTextColor={Colors.textSecondary}
            multiline
            maxLength={500}
            returnKeyType="send"
            onSubmitEditing={sendMessage}
            blurOnSubmit={false}
          />
          <TouchableOpacity
            style={[
              styles.sendButton,
              (!input.trim() || loading) && styles.sendButtonDisabled,
            ]}
            onPress={sendMessage}
            disabled={!input.trim() || loading}
          >
            <Ionicons name="send" size={20} color="#ffffff" />
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  messageList: {
    paddingVertical: 12,
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  emptyText: {
    fontSize: 16,
    color: Colors.textSecondary,
    marginTop: 12,
  },
  emptyHint: {
    fontSize: 13,
    color: Colors.border,
    marginTop: 4,
    fontStyle: "italic",
  },
  domainBadges: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingTop: 8,
    gap: 6,
  },
  badge: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  badgeText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
  },
  loadingBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  loadingText: {
    marginLeft: 8,
    fontSize: 13,
    color: Colors.textSecondary,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.inputBg,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.text,
    maxHeight: 100,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  sendButtonDisabled: {
    backgroundColor: Colors.border,
  },
});
